# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,4,7],[2,4,3]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,4,8],
                [2,7,7]],
               [[1,6,7],
               [2,4,8]]])

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a2data = pd.DataFrame(a2)
a2data

0  1  2
0  1  4  7
1  2  4  3

In [13]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10,size=(7,2))
random_array

array([[1, 9],
       [1, 2],
       [5, 0],
       [1, 5],
       [2, 4],
       [1, 4],
       [7, 1]])

In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_1 = np.random.random((3,5))
random_array_1

array([[0.50707078, 0.06498652, 0.97053052, 0.35059239, 0.42299461],
       [0.70476945, 0.95705702, 0.46527522, 0.45622322, 0.26120595],
       [0.07989769, 0.97650657, 0.37451807, 0.16224851, 0.48723116]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [31]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [32]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [33]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]

array([[9, 1],
       [5, 3]])

In [40]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(0,10,(3,5))
ones = np.ones((3,5))

In [41]:
# Add the two arrays together
a4 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [42]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [43]:
# Try add the array of ones and the other most recent array together
a4+ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [44]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [45]:
# Subtract the new array of ones from the other most recent array
a4 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [46]:
# Multiply the ones array with the latest array
a4 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [48]:
# Take the latest array to the power of 2 using '**'
a4 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [49]:
# Do the same thing with np.square()
np.square(a4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [50]:
# Find the mean of the latest array using np.mean()
np.mean(a4)

3.8666666666666667

In [51]:
# Find the maximum of the latest array using np.max()
np.max(a4)

9

In [52]:
# Find the minimum of the latest array using np.min()
np.min(a4)

0

In [53]:
# Find the standard deviation of the latest array
np.std(a4)

2.578543947441829

In [54]:
# Find the variance of the latest array
np.var(a4)

6.648888888888889

In [55]:
# Reshape the latest array to (3, 5, 1)
a4.reshape((3,5,1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [56]:
# Transpose the latest array
a4.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

In [57]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a5 = np.random.randint(0,10,(3,3))
a6 = np.random.randint(0,10,(3,2))

In [58]:
# Perform a dot product on the two newest arrays you created
np.dot(a5,a6)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [61]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a7 = np.random.randint(0,10,(4,3))
a8 = np.random.randint(0,10,(4,3))

In [62]:
# Perform a dot product on the two newest arrays you created
np.dot(a7,a8)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [68]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a7.T,a8)

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

In [69]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a9 = np.random.randint(0,10,(4,3))
a10 = np.random.randint(0,10,(4,3))

In [70]:
# Compare the two arrays with '>'
a9 > a10

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [71]:
# Compare the two arrays with '>='
a9 >= a10

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [72]:
# Find which elements of the first array are greater than 7
a9 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [73]:
# Which parts of each array are equal? (try using '==')
a9 == a10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [74]:
# Sort one of the arrays you just created in ascending order
np.sort(a9)

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5],
       [2, 2, 4]])

In [75]:
# Sort the indexes of one of the arrays you just created
np.argsort(a9)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0],
       [0, 2, 1]], dtype=int64)

In [76]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a9)

2

In [77]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a9)

8

In [78]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a9, axis=1)

array([2, 2, 0, 1], dtype=int64)

In [79]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a9, axis=0)

array([3, 1, 2], dtype=int64)

In [80]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966,  0.70498131,  0.36092338],
       [-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463]])

In [81]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.